swagger: "2.0"
info: { version: "", title: "" }

paths: { }

definitions:
  Artifact:
    type: object
    required: [ name ]
    properties:
      name: { type: string, example: "2.2.2.2" }
      type: { type: string }
      kind: { type: string }
      status: { type: string, example: "Unknown" }
      enrichments: { type: object, additionalProperties: { $ref: "#/definitions/Enrichment" } }

  EnrichmentForm:
    type: object
    required: [ name, data ]
    properties:
      name: { type: string, example: "hash.sha1" }
      data: { type: object, example: { "hash": "b7a067a742c20d07a7456646de89bc2d408a1153" } }

  Enrichment:
    type: object
    required: [ name, data, created ]
    properties:
      name: { type: string, example: "hash.sha1" }
      data: { type: object, example: { "hash": "b7a067a742c20d07a7456646de89bc2d408a1153" } }
      created: { type: string, format: "date-time", example: "1985-04-12T23:20:50.52Z" }
