swagger: "2.0"
info: { version: "", title: "" }

paths:
  /statistics:
    get:
      tags: [ "statistics" ]
      summary: "Get statistics"
      operationId: "getStatistics"
      responses:
        "200":
          description: "successful operation"
          schema: { $ref: '#/definitions/Statistics' }
          examples:
            test:
              unassigned: 0
              open_tickets_per_user: { }
              tickets_per_week: { "2021-39": 3 }
              tickets_per_type: { "alert": 2, "incident": 1 }
      security: [ { roles: [ "ticket:read" ] } ]

definitions:

  Statistics:
    type: object
    required: [ unassigned, open_tickets_per_user, tickets_per_week, tickets_per_type ]
    properties:
      unassigned: { type: integer }
      open_tickets_per_user: { type: object, additionalProperties: { type: integer } }
      tickets_per_week: { type: object, additionalProperties: { type: integer } }
      tickets_per_type: { type: object, additionalProperties: { type: integer } }
