swagger: "2.0"
info:
  version: "0.0.3"
  title: "Catalyst"
  description: API for the catalyst incident response platform.

host: "."
basePath: "/api"
schemes:
  # - "https"
  - "http"

consumes: [ "application/json" ]
produces: [ "application/json" ]

paths: {}

definitions: {}
