run:
  go: "1.22"
  timeout: 5m
linters:
  enable-all: true
  disable:
    # complexity
    - maintidx
    - funlen

    # disable
    - depguard
    - dupl
    - err113
    - exhaustruct
    - gochecknoglobals
    - godox
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - perfsprint
    - prealloc
    - tagalign
    - tagliatelle
    - tenv
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/SecurityBrewery/catalyst)
