version: "2"
run:
  go: "1.22"
linters:
  default: all
  disable:
    - depguard
    - dupl
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - godox
    - ireturn
    - lll
    - maintidx
    - mnd
    - nonamedreturns
    - perfsprint
    - prealloc
    - tagalign
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/SecurityBrewery/catalyst)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
