run:
  go: "1.22"
  timeout: 5m
linters:
  enable-all: true
  disable:
    # complexity
    - cyclop
    - gocognit
    - gocyclo
    - maintidx
    - nestif

    # disable
    - depguard
    - dupl
    - err113
    - execinquery
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - godox
    - gomnd
    - gomoddirectives
    - ireturn
    - lll
    - makezero
    - mnd
    - prealloc
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/SecurityBrewery/catalyst)
