run:
  go: "1.22"
  timeout: 5m
linters:
  enable-all: true
  disable:
    # complexity
    - maintidx
    - funlen

    # disable
    - depguard
    - err113
    - exhaustruct
    - gomnd
    - ireturn
    - lll
    - mnd
    - testpackage
    - varnamelen
    - wrapcheck
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/SecurityBrewery/catalyst)
