version: '2.2'
services:
  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: [ "80:80", "8529:8529", "9000:9000", "9001:9001", "9002:9002" ]

  arangodb:
    image: arangodb/arangodb:3.8.1
    environment:
      ARANGO_ROOT_PASSWORD: foobar

  emitter:
    image: emitter/server
    environment:
      - EMITTER_LICENSE=PfA8ID8izeSlDUlNZgNXo77DQV9QzlNtxTk64WreCXKfDZsREAVXUXwh20UKOZdkALbLTmOytO_iC6mc_twKAQ:3
      # A9RysEsPJni8RaHeg_K0FKXQNfBrUyw-

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data -console-address ":9003"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - ./keycloak/realm.json:/tmp/realm.json
    depends_on: [ postgres ]
