/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DashboardCounts
 */
export interface DashboardCounts {
    /**
     * 
     * @type {string}
     * @memberof DashboardCounts
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof DashboardCounts
     */
    count: number;
}

/**
 * Check if a given object implements the DashboardCounts interface.
 */
export function instanceOfDashboardCounts(value: object): value is DashboardCounts {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function DashboardCountsFromJSON(json: any): DashboardCounts {
    return DashboardCountsFromJSONTyped(json, false);
}

export function DashboardCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardCounts {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'count': json['count'],
    };
}

export function DashboardCountsToJSON(json: any): DashboardCounts {
    return DashboardCountsToJSONTyped(json, false);
}

export function DashboardCountsToJSONTyped(value?: DashboardCounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'count': value['count'],
    };
}

