/* tslint:disable */

/* eslint-disable */

/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface Files
 */
export interface Files {
  /**
   *
   * @type {string}
   * @memberof Files
   */
  blob: string
  /**
   *
   * @type {string}
   * @memberof Files
   */
  created: string
  /**
   *
   * @type {string}
   * @memberof Files
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof Files
   */
  name: string
  /**
   *
   * @type {number}
   * @memberof Files
   */
  size: number
  /**
   *
   * @type {string}
   * @memberof Files
   */
  ticket: string
  /**
   *
   * @type {string}
   * @memberof Files
   */
  updated: string
}

/**
 * Check if a given object implements the Files interface.
 */
export function instanceOfFiles(value: object): value is Files {
  if (!('blob' in value) || value['blob'] === undefined) return false
  if (!('created' in value) || value['created'] === undefined) return false
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('size' in value) || value['size'] === undefined) return false
  if (!('ticket' in value) || value['ticket'] === undefined) return false
  if (!('updated' in value) || value['updated'] === undefined) return false
  return true
}

export function FilesFromJSON(json: any): Files {
  return FilesFromJSONTyped(json, false)
}

export function FilesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Files {
  if (json == null) {
    return json
  }
  return {
    blob: json['blob'],
    created: json['created'],
    id: json['id'],
    name: json['name'],
    size: json['size'],
    ticket: json['ticket'],
    updated: json['updated']
  }
}

export function FilesToJSON(json: any): Files {
  return FilesToJSONTyped(json, false)
}

export function FilesToJSONTyped(value?: Files | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    blob: value['blob'],
    created: value['created'],
    id: value['id'],
    name: value['name'],
    size: value['size'],
    ticket: value['ticket'],
    updated: value['updated']
  }
}
