/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface GroupRelation
 */
export interface GroupRelation {
  /**
   *
   * @type {string}
   * @memberof GroupRelation
   */
  groupId: string
}

/**
 * Check if a given object implements the GroupRelation interface.
 */
export function instanceOfGroupRelation(value: object): value is GroupRelation {
  if (!('groupId' in value) || value['groupId'] === undefined) return false
  return true
}

export function GroupRelationFromJSON(json: any): GroupRelation {
  return GroupRelationFromJSONTyped(json, false)
}

export function GroupRelationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupRelation {
  if (json == null) {
    return json
  }
  return {
    groupId: json['group_id']
  }
}

export function GroupRelationToJSON(json: any): GroupRelation {
  return GroupRelationToJSONTyped(json, false)
}

export function GroupRelationToJSONTyped(
  value?: GroupRelation | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    group_id: value['groupId']
  }
}
