/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewFeature
 */
export interface NewFeature {
    /**
     * 
     * @type {string}
     * @memberof NewFeature
     */
    name: string;
}

/**
 * Check if a given object implements the NewFeature interface.
 */
export function instanceOfNewFeature(value: object): value is NewFeature {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NewFeatureFromJSON(json: any): NewFeature {
    return NewFeatureFromJSONTyped(json, false);
}

export function NewFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewFeature {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function NewFeatureToJSON(json: any): NewFeature {
    return NewFeatureToJSONTyped(json, false);
}

export function NewFeatureToJSONTyped(value?: NewFeature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

