/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewLink
 */
export interface NewLink {
    /**
     * 
     * @type {string}
     * @memberof NewLink
     */
    ticket: string;
    /**
     * 
     * @type {string}
     * @memberof NewLink
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NewLink
     */
    url: string;
}

/**
 * Check if a given object implements the NewLink interface.
 */
export function instanceOfNewLink(value: object): value is NewLink {
    if (!('ticket' in value) || value['ticket'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function NewLinkFromJSON(json: any): NewLink {
    return NewLinkFromJSONTyped(json, false);
}

export function NewLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewLink {
    if (json == null) {
        return json;
    }
    return {
        
        'ticket': json['ticket'],
        'name': json['name'],
        'url': json['url'],
    };
}

export function NewLinkToJSON(json: any): NewLink {
    return NewLinkToJSONTyped(json, false);
}

export function NewLinkToJSONTyped(value?: NewLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ticket': value['ticket'],
        'name': value['name'],
        'url': value['url'],
    };
}

