/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Reactions
 */
export interface Reactions {
    /**
     * 
     * @type {string}
     * @memberof Reactions
     */
    action: string;
    /**
     * 
     * @type {object}
     * @memberof Reactions
     */
    actiondata: object;
    /**
     * 
     * @type {string}
     * @memberof Reactions
     */
    created: string;
    /**
     * 
     * @type {string}
     * @memberof Reactions
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Reactions
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Reactions
     */
    trigger: string;
    /**
     * 
     * @type {object}
     * @memberof Reactions
     */
    triggerdata: object;
    /**
     * 
     * @type {string}
     * @memberof Reactions
     */
    updated: string;
}

/**
 * Check if a given object implements the Reactions interface.
 */
export function instanceOfReactions(value: object): value is Reactions {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('actiondata' in value) || value['actiondata'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('trigger' in value) || value['trigger'] === undefined) return false;
    if (!('triggerdata' in value) || value['triggerdata'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    return true;
}

export function ReactionsFromJSON(json: any): Reactions {
    return ReactionsFromJSONTyped(json, false);
}

export function ReactionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reactions {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'actiondata': json['actiondata'],
        'created': json['created'],
        'id': json['id'],
        'name': json['name'],
        'trigger': json['trigger'],
        'triggerdata': json['triggerdata'],
        'updated': json['updated'],
    };
}

export function ReactionsToJSON(json: any): Reactions {
    return ReactionsToJSONTyped(json, false);
}

export function ReactionsToJSONTyped(value?: Reactions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'actiondata': value['actiondata'],
        'created': value['created'],
        'id': value['id'],
        'name': value['name'],
        'trigger': value['trigger'],
        'triggerdata': value['triggerdata'],
        'updated': value['updated'],
    };
}

