/* tslint:disable */

/* eslint-disable */

/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface RoleUser
 */
export interface RoleUser {
  /**
   *
   * @type {string}
   * @memberof RoleUser
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof RoleUser
   */
  username: string
  /**
   *
   * @type {string}
   * @memberof RoleUser
   */
  avatar: string
  /**
   *
   * @type {string}
   * @memberof RoleUser
   */
  email: string
  /**
   *
   * @type {boolean}
   * @memberof RoleUser
   */
  emailVisibility: boolean
  /**
   *
   * @type {string}
   * @memberof RoleUser
   */
  lastLoginAlertSentAt: string
  /**
   *
   * @type {string}
   * @memberof RoleUser
   */
  lastResetSentAt: string
  /**
   *
   * @type {string}
   * @memberof RoleUser
   */
  lastVerificationSentAt: string
  /**
   *
   * @type {string}
   * @memberof RoleUser
   */
  name: string
  /**
   *
   * @type {boolean}
   * @memberof RoleUser
   */
  verified: boolean
  /**
   *
   * @type {string}
   * @memberof RoleUser
   */
  type: string
  /**
   *
   * @type {string}
   * @memberof RoleUser
   */
  created: string
  /**
   *
   * @type {string}
   * @memberof RoleUser
   */
  updated: string
}

/**
 * Check if a given object implements the RoleUser interface.
 */
export function instanceOfRoleUser(value: object): value is RoleUser {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('username' in value) || value['username'] === undefined) return false
  if (!('avatar' in value) || value['avatar'] === undefined) return false
  if (!('email' in value) || value['email'] === undefined) return false
  if (!('emailVisibility' in value) || value['emailVisibility'] === undefined) return false
  if (!('lastLoginAlertSentAt' in value) || value['lastLoginAlertSentAt'] === undefined)
    return false
  if (!('lastResetSentAt' in value) || value['lastResetSentAt'] === undefined) return false
  if (!('lastVerificationSentAt' in value) || value['lastVerificationSentAt'] === undefined)
    return false
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('verified' in value) || value['verified'] === undefined) return false
  if (!('type' in value) || value['type'] === undefined) return false
  if (!('created' in value) || value['created'] === undefined) return false
  if (!('updated' in value) || value['updated'] === undefined) return false
  return true
}

export function RoleUserFromJSON(json: any): RoleUser {
  return RoleUserFromJSONTyped(json, false)
}

export function RoleUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleUser {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    username: json['username'],
    avatar: json['avatar'],
    email: json['email'],
    emailVisibility: json['emailVisibility'],
    lastLoginAlertSentAt: json['lastLoginAlertSentAt'],
    lastResetSentAt: json['lastResetSentAt'],
    lastVerificationSentAt: json['lastVerificationSentAt'],
    name: json['name'],
    verified: json['verified'],
    type: json['type'],
    created: json['created'],
    updated: json['updated']
  }
}

export function RoleUserToJSON(json: any): RoleUser {
  return RoleUserToJSONTyped(json, false)
}

export function RoleUserToJSONTyped(
  value?: RoleUser | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    username: value['username'],
    avatar: value['avatar'],
    email: value['email'],
    emailVisibility: value['emailVisibility'],
    lastLoginAlertSentAt: value['lastLoginAlertSentAt'],
    lastResetSentAt: value['lastResetSentAt'],
    lastVerificationSentAt: value['lastVerificationSentAt'],
    name: value['name'],
    verified: value['verified'],
    type: value['type'],
    created: value['created'],
    updated: value['updated']
  }
}
