/* tslint:disable */

/* eslint-disable */

/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface RoleRelation
 */
export interface RoleRelation {
  /**
   *
   * @type {string}
   * @memberof RoleRelation
   */
  roleId: string
}

/**
 * Check if a given object implements the RoleRelation interface.
 */
export function instanceOfRoleRelation(value: object): value is RoleRelation {
  if (!('roleId' in value) || value['roleId'] === undefined) return false
  return true
}

export function RoleRelationFromJSON(json: any): RoleRelation {
  return RoleRelationFromJSONTyped(json, false)
}

export function RoleRelationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleRelation {
  if (json == null) {
    return json
  }
  return {
    roleId: json['role_id']
  }
}

export function RoleRelationToJSON(json: any): RoleRelation {
  return RoleRelationToJSONTyped(json, false)
}

export function RoleRelationToJSONTyped(
  value?: RoleRelation | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    role_id: value['roleId']
  }
}
