/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tasks
 */
export interface Tasks {
    /**
     * 
     * @type {string}
     * @memberof Tasks
     */
    created: string;
    /**
     * 
     * @type {string}
     * @memberof Tasks
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Tasks
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof Tasks
     */
    open: boolean;
    /**
     * 
     * @type {string}
     * @memberof Tasks
     */
    owner: string;
    /**
     * 
     * @type {string}
     * @memberof Tasks
     */
    ticket: string;
    /**
     * 
     * @type {string}
     * @memberof Tasks
     */
    updated: string;
}

/**
 * Check if a given object implements the Tasks interface.
 */
export function instanceOfTasks(value: object): value is Tasks {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('open' in value) || value['open'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('ticket' in value) || value['ticket'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    return true;
}

export function TasksFromJSON(json: any): Tasks {
    return TasksFromJSONTyped(json, false);
}

export function TasksFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tasks {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'],
        'id': json['id'],
        'name': json['name'],
        'open': json['open'],
        'owner': json['owner'],
        'ticket': json['ticket'],
        'updated': json['updated'],
    };
}

export function TasksToJSON(json: any): Tasks {
    return TasksToJSONTyped(json, false);
}

export function TasksToJSONTyped(value?: Tasks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'id': value['id'],
        'name': value['name'],
        'open': value['open'],
        'owner': value['owner'],
        'ticket': value['ticket'],
        'updated': value['updated'],
    };
}

