/* tslint:disable */

/* eslint-disable */

/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface Timeline
 */
export interface Timeline {
  /**
   *
   * @type {string}
   * @memberof Timeline
   */
  created: string
  /**
   *
   * @type {string}
   * @memberof Timeline
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof Timeline
   */
  message: string
  /**
   *
   * @type {string}
   * @memberof Timeline
   */
  ticket: string
  /**
   *
   * @type {string}
   * @memberof Timeline
   */
  time: string
  /**
   *
   * @type {string}
   * @memberof Timeline
   */
  updated: string
}

/**
 * Check if a given object implements the Timeline interface.
 */
export function instanceOfTimeline(value: object): value is Timeline {
  if (!('created' in value) || value['created'] === undefined) return false
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('message' in value) || value['message'] === undefined) return false
  if (!('ticket' in value) || value['ticket'] === undefined) return false
  if (!('time' in value) || value['time'] === undefined) return false
  if (!('updated' in value) || value['updated'] === undefined) return false
  return true
}

export function TimelineFromJSON(json: any): Timeline {
  return TimelineFromJSONTyped(json, false)
}

export function TimelineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Timeline {
  if (json == null) {
    return json
  }
  return {
    created: json['created'],
    id: json['id'],
    message: json['message'],
    ticket: json['ticket'],
    time: json['time'],
    updated: json['updated']
  }
}

export function TimelineToJSON(json: any): Timeline {
  return TimelineToJSONTyped(json, false)
}

export function TimelineToJSONTyped(
  value?: Timeline | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    created: value['created'],
    id: value['id'],
    message: value['message'],
    ticket: value['ticket'],
    time: value['time'],
    updated: value['updated']
  }
}
