/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface TokenConfig
 */
export interface TokenConfig {
  /**
   *
   * @type {string}
   * @memberof TokenConfig
   */
  secret: string
  /**
   *
   * @type {number}
   * @memberof TokenConfig
   */
  duration: number
}

/**
 * Check if a given object implements the TokenConfig interface.
 */
export function instanceOfTokenConfig(value: object): value is TokenConfig {
  if (!('secret' in value) || value['secret'] === undefined) return false
  if (!('duration' in value) || value['duration'] === undefined) return false
  return true
}

export function TokenConfigFromJSON(json: any): TokenConfig {
  return TokenConfigFromJSONTyped(json, false)
}

export function TokenConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenConfig {
  if (json == null) {
    return json
  }
  return {
    secret: json['secret'],
    duration: json['duration']
  }
}

export function TokenConfigToJSON(json: any): TokenConfig {
  return TokenConfigToJSONTyped(json, false)
}

export function TokenConfigToJSONTyped(
  value?: TokenConfig | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    secret: value['secret'],
    duration: value['duration']
  }
}
