/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Webhook
 */
export interface Webhook {
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    collection: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    created: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    destination: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    updated: string;
}

/**
 * Check if a given object implements the Webhook interface.
 */
export function instanceOfWebhook(value: object): value is Webhook {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    return true;
}

export function WebhookFromJSON(json: any): Webhook {
    return WebhookFromJSONTyped(json, false);
}

export function WebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Webhook {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': json['collection'],
        'created': json['created'],
        'destination': json['destination'],
        'id': json['id'],
        'name': json['name'],
        'updated': json['updated'],
    };
}

export function WebhookToJSON(json: any): Webhook {
    return WebhookToJSONTyped(json, false);
}

export function WebhookToJSONTyped(value?: Webhook | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': value['collection'],
        'created': value['created'],
        'destination': value['destination'],
        'id': value['id'],
        'name': value['name'],
        'updated': value['updated'],
    };
}

