services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
    ports:
      - "8081:8080"

  authelia:
    # image: authelia/authelia:latest
    build:
      context: authelia
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8082:8082"
