// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: read.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getComment = `-- name: GetComment :one

SELECT comments.author, comments.created, comments.id, comments.message, comments.ticket, comments.updated, users.name as author_name
FROM comments
         LEFT JOIN users ON users.id = comments.author
WHERE comments.id = ?1
`

type GetCommentRow struct {
	Author     string         `json:"author"`
	Created    string         `json:"created"`
	ID         string         `json:"id"`
	Message    string         `json:"message"`
	Ticket     string         `json:"ticket"`
	Updated    string         `json:"updated"`
	AuthorName sql.NullString `json:"author_name"`
}

// ----------------------------------------------------------------
func (q *ReadQueries) GetComment(ctx context.Context, id string) (GetCommentRow, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i GetCommentRow
	err := row.Scan(
		&i.Author,
		&i.Created,
		&i.ID,
		&i.Message,
		&i.Ticket,
		&i.Updated,
		&i.AuthorName,
	)
	return i, err
}

const getDashboardCounts = `-- name: GetDashboardCounts :many

SELECT id, count
FROM dashboard_counts
`

// ----------------------------------------------------------------
func (q *ReadQueries) GetDashboardCounts(ctx context.Context) ([]DashboardCount, error) {
	rows, err := q.db.QueryContext(ctx, getDashboardCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardCount
	for rows.Next() {
		var i DashboardCount
		if err := rows.Scan(&i.ID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeature = `-- name: GetFeature :one

SELECT created, id, name, updated
FROM features
WHERE id = ?1
`

// ----------------------------------------------------------------
func (q *ReadQueries) GetFeature(ctx context.Context, id string) (Feature, error) {
	row := q.db.QueryRowContext(ctx, getFeature, id)
	var i Feature
	err := row.Scan(
		&i.Created,
		&i.ID,
		&i.Name,
		&i.Updated,
	)
	return i, err
}

const getFile = `-- name: GetFile :one

SELECT blob, created, id, name, size, ticket, updated
FROM files
WHERE id = ?1
`

// ----------------------------------------------------------------
func (q *ReadQueries) GetFile(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.Blob,
		&i.Created,
		&i.ID,
		&i.Name,
		&i.Size,
		&i.Ticket,
		&i.Updated,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one

SELECT id, name, permissions, created, updated
FROM groups
WHERE id = ?1
`

// ----------------------------------------------------------------
func (q *ReadQueries) GetGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Permissions,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getLink = `-- name: GetLink :one

SELECT created, id, name, ticket, updated, url
FROM links
WHERE id = ?1
`

// ----------------------------------------------------------------
func (q *ReadQueries) GetLink(ctx context.Context, id string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.Created,
		&i.ID,
		&i.Name,
		&i.Ticket,
		&i.Updated,
		&i.Url,
	)
	return i, err
}

const getReaction = `-- name: GetReaction :one

SELECT "action", actiondata, created, id, name, "trigger", triggerdata, updated
FROM reactions
WHERE id = ?1
`

// ----------------------------------------------------------------
func (q *ReadQueries) GetReaction(ctx context.Context, id string) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, getReaction, id)
	var i Reaction
	err := row.Scan(
		&i.Action,
		&i.Actiondata,
		&i.Created,
		&i.ID,
		&i.Name,
		&i.Trigger,
		&i.Triggerdata,
		&i.Updated,
	)
	return i, err
}

const getSidebar = `-- name: GetSidebar :many
SELECT id, singular, plural, icon, count
FROM sidebar
`

func (q *ReadQueries) GetSidebar(ctx context.Context) ([]Sidebar, error) {
	rows, err := q.db.QueryContext(ctx, getSidebar)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sidebar
	for rows.Next() {
		var i Sidebar
		if err := rows.Scan(
			&i.ID,
			&i.Singular,
			&i.Plural,
			&i.Icon,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one

SELECT tasks.created, tasks.id, tasks.name, tasks.open, tasks.owner, tasks.ticket, tasks.updated, users.name as owner_name, tickets.name as ticket_name, tickets.type as ticket_type
FROM tasks
         LEFT JOIN users ON users.id = tasks.owner
         LEFT JOIN tickets ON tickets.id = tasks.ticket
WHERE tasks.id = ?1
`

type GetTaskRow struct {
	Created    string         `json:"created"`
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Open       bool           `json:"open"`
	Owner      string         `json:"owner"`
	Ticket     string         `json:"ticket"`
	Updated    string         `json:"updated"`
	OwnerName  sql.NullString `json:"owner_name"`
	TicketName sql.NullString `json:"ticket_name"`
	TicketType sql.NullString `json:"ticket_type"`
}

// ----------------------------------------------------------------
func (q *ReadQueries) GetTask(ctx context.Context, id string) (GetTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.Created,
		&i.ID,
		&i.Name,
		&i.Open,
		&i.Owner,
		&i.Ticket,
		&i.Updated,
		&i.OwnerName,
		&i.TicketName,
		&i.TicketType,
	)
	return i, err
}

const getTimeline = `-- name: GetTimeline :one

SELECT created, id, message, ticket, time, updated
FROM timeline
WHERE id = ?1
`

// ----------------------------------------------------------------
func (q *ReadQueries) GetTimeline(ctx context.Context, id string) (Timeline, error) {
	row := q.db.QueryRowContext(ctx, getTimeline, id)
	var i Timeline
	err := row.Scan(
		&i.Created,
		&i.ID,
		&i.Message,
		&i.Ticket,
		&i.Time,
		&i.Updated,
	)
	return i, err
}

const getType = `-- name: GetType :one

SELECT created, icon, id, plural, schema, singular, updated
FROM types
WHERE id = ?1
`

// ----------------------------------------------------------------
func (q *ReadQueries) GetType(ctx context.Context, id string) (Type, error) {
	row := q.db.QueryRowContext(ctx, getType, id)
	var i Type
	err := row.Scan(
		&i.Created,
		&i.Icon,
		&i.ID,
		&i.Plural,
		&i.Schema,
		&i.Singular,
		&i.Updated,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT avatar, created, email, id, lastresetsentat, lastverificationsentat, name, passwordhash, tokenkey, updated, username, verified
FROM users
WHERE id = ?1
  AND id != 'system'
`

// ----------------------------------------------------------------
func (q *ReadQueries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.Avatar,
		&i.Created,
		&i.Email,
		&i.ID,
		&i.Lastresetsentat,
		&i.Lastverificationsentat,
		&i.Name,
		&i.Passwordhash,
		&i.Tokenkey,
		&i.Updated,
		&i.Username,
		&i.Verified,
	)
	return i, err
}

const getWebhook = `-- name: GetWebhook :one

SELECT collection, created, destination, id, name, updated
FROM webhooks
WHERE id = ?1
`

// ----------------------------------------------------------------
func (q *ReadQueries) GetWebhook(ctx context.Context, id string) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.Collection,
		&i.Created,
		&i.Destination,
		&i.ID,
		&i.Name,
		&i.Updated,
	)
	return i, err
}

const listChildGroups = `-- name: ListChildGroups :many
SELECT g.id, g.name, g.permissions, g.created, g.updated, group_effective_groups.group_type
FROM group_effective_groups
         JOIN groups AS g ON g.id = group_effective_groups.parent_group_id
WHERE child_group_id = ?1
ORDER BY group_effective_groups.group_type
`

type ListChildGroupsRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Permissions string `json:"permissions"`
	Created     string `json:"created"`
	Updated     string `json:"updated"`
	GroupType   string `json:"group_type"`
}

func (q *ReadQueries) ListChildGroups(ctx context.Context, groupID string) ([]ListChildGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChildGroups, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildGroupsRow
	for rows.Next() {
		var i ListChildGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Permissions,
			&i.Created,
			&i.Updated,
			&i.GroupType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT comments.author, comments.created, comments.id, comments.message, comments.ticket, comments.updated, users.name as author_name, COUNT(*) OVER () as total_count
FROM comments
         LEFT JOIN users ON users.id = comments.author
WHERE ticket = ?1
   OR ?1 = ''
ORDER BY comments.created DESC
LIMIT ?3 OFFSET ?2
`

type ListCommentsParams struct {
	Ticket string `json:"ticket"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type ListCommentsRow struct {
	Author     string         `json:"author"`
	Created    string         `json:"created"`
	ID         string         `json:"id"`
	Message    string         `json:"message"`
	Ticket     string         `json:"ticket"`
	Updated    string         `json:"updated"`
	AuthorName sql.NullString `json:"author_name"`
	TotalCount int64          `json:"total_count"`
}

func (q *ReadQueries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listComments, arg.Ticket, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.Author,
			&i.Created,
			&i.ID,
			&i.Message,
			&i.Ticket,
			&i.Updated,
			&i.AuthorName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatures = `-- name: ListFeatures :many
SELECT features.created, features.id, features.name, features.updated, COUNT(*) OVER () as total_count
FROM features
ORDER BY features.created DESC
LIMIT ?2 OFFSET ?1
`

type ListFeaturesParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListFeaturesRow struct {
	Created    string `json:"created"`
	ID         string `json:"id"`
	Name       string `json:"name"`
	Updated    string `json:"updated"`
	TotalCount int64  `json:"total_count"`
}

func (q *ReadQueries) ListFeatures(ctx context.Context, arg ListFeaturesParams) ([]ListFeaturesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeatures, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeaturesRow
	for rows.Next() {
		var i ListFeaturesRow
		if err := rows.Scan(
			&i.Created,
			&i.ID,
			&i.Name,
			&i.Updated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiles = `-- name: ListFiles :many
SELECT files.blob, files.created, files.id, files.name, files.size, files.ticket, files.updated, COUNT(*) OVER () as total_count
FROM files
WHERE ticket = ?1
   OR ?1 = ''
ORDER BY files.created DESC
LIMIT ?3 OFFSET ?2
`

type ListFilesParams struct {
	Ticket string `json:"ticket"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type ListFilesRow struct {
	Blob       string  `json:"blob"`
	Created    string  `json:"created"`
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Size       float64 `json:"size"`
	Ticket     string  `json:"ticket"`
	Updated    string  `json:"updated"`
	TotalCount int64   `json:"total_count"`
}

func (q *ReadQueries) ListFiles(ctx context.Context, arg ListFilesParams) ([]ListFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFiles, arg.Ticket, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesRow
	for rows.Next() {
		var i ListFilesRow
		if err := rows.Scan(
			&i.Blob,
			&i.Created,
			&i.ID,
			&i.Name,
			&i.Size,
			&i.Ticket,
			&i.Updated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupUsers = `-- name: ListGroupUsers :many
SELECT users.avatar, users.created, users.email, users.id, users.lastresetsentat, users.lastverificationsentat, users.name, users.passwordhash, users.tokenkey, users.updated, users.username, users.verified, uer.group_type
FROM user_effective_groups uer
         JOIN users ON users.id = uer.user_id
WHERE uer.group_id = ?1
ORDER BY users.name DESC
`

type ListGroupUsersRow struct {
	Avatar                 string `json:"avatar"`
	Created                string `json:"created"`
	Email                  string `json:"email"`
	ID                     string `json:"id"`
	Lastresetsentat        string `json:"lastresetsentat"`
	Lastverificationsentat string `json:"lastverificationsentat"`
	Name                   string `json:"name"`
	Passwordhash           string `json:"passwordhash"`
	Tokenkey               string `json:"tokenkey"`
	Updated                string `json:"updated"`
	Username               string `json:"username"`
	Verified               bool   `json:"verified"`
	GroupType              string `json:"group_type"`
}

func (q *ReadQueries) ListGroupUsers(ctx context.Context, groupID string) ([]ListGroupUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupUsers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupUsersRow
	for rows.Next() {
		var i ListGroupUsersRow
		if err := rows.Scan(
			&i.Avatar,
			&i.Created,
			&i.Email,
			&i.ID,
			&i.Lastresetsentat,
			&i.Lastverificationsentat,
			&i.Name,
			&i.Passwordhash,
			&i.Tokenkey,
			&i.Updated,
			&i.Username,
			&i.Verified,
			&i.GroupType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.name, g.permissions, g.created, g.updated, COUNT(*) OVER () as total_count
FROM groups AS g
ORDER BY g.created DESC
LIMIT ?2 OFFSET ?1
`

type ListGroupsParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListGroupsRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Permissions string `json:"permissions"`
	Created     string `json:"created"`
	Updated     string `json:"updated"`
	TotalCount  int64  `json:"total_count"`
}

func (q *ReadQueries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]ListGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroups, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Permissions,
			&i.Created,
			&i.Updated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinks = `-- name: ListLinks :many
SELECT links.created, links.id, links.name, links.ticket, links.updated, links.url, COUNT(*) OVER () as total_count
FROM links
WHERE ticket = ?1
   OR ?1 = ''
ORDER BY links.created DESC
LIMIT ?3 OFFSET ?2
`

type ListLinksParams struct {
	Ticket string `json:"ticket"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type ListLinksRow struct {
	Created    string `json:"created"`
	ID         string `json:"id"`
	Name       string `json:"name"`
	Ticket     string `json:"ticket"`
	Updated    string `json:"updated"`
	Url        string `json:"url"`
	TotalCount int64  `json:"total_count"`
}

func (q *ReadQueries) ListLinks(ctx context.Context, arg ListLinksParams) ([]ListLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinks, arg.Ticket, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksRow
	for rows.Next() {
		var i ListLinksRow
		if err := rows.Scan(
			&i.Created,
			&i.ID,
			&i.Name,
			&i.Ticket,
			&i.Updated,
			&i.Url,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentGroups = `-- name: ListParentGroups :many
SELECT g.id, g.name, g.permissions, g.created, g.updated, group_effective_groups.group_type
FROM group_effective_groups
         JOIN groups AS g ON g.id = group_effective_groups.child_group_id
WHERE parent_group_id = ?1
ORDER BY group_effective_groups.group_type
`

type ListParentGroupsRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Permissions string `json:"permissions"`
	Created     string `json:"created"`
	Updated     string `json:"updated"`
	GroupType   string `json:"group_type"`
}

func (q *ReadQueries) ListParentGroups(ctx context.Context, groupID string) ([]ListParentGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listParentGroups, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParentGroupsRow
	for rows.Next() {
		var i ListParentGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Permissions,
			&i.Created,
			&i.Updated,
			&i.GroupType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentPermissions = `-- name: ListParentPermissions :many
SELECT group_effective_permissions.permission
FROM group_effective_permissions
WHERE parent_group_id = ?1
ORDER BY permission
`

func (q *ReadQueries) ListParentPermissions(ctx context.Context, groupID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listParentPermissions, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactions = `-- name: ListReactions :many
SELECT reactions."action", reactions.actiondata, reactions.created, reactions.id, reactions.name, reactions."trigger", reactions.triggerdata, reactions.updated, COUNT(*) OVER () as total_count
FROM reactions
ORDER BY reactions.created DESC
LIMIT ?2 OFFSET ?1
`

type ListReactionsParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListReactionsRow struct {
	Action      string `json:"action"`
	Actiondata  string `json:"actiondata"`
	Created     string `json:"created"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	Trigger     string `json:"trigger"`
	Triggerdata string `json:"triggerdata"`
	Updated     string `json:"updated"`
	TotalCount  int64  `json:"total_count"`
}

func (q *ReadQueries) ListReactions(ctx context.Context, arg ListReactionsParams) ([]ListReactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactions, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReactionsRow
	for rows.Next() {
		var i ListReactionsRow
		if err := rows.Scan(
			&i.Action,
			&i.Actiondata,
			&i.Created,
			&i.ID,
			&i.Name,
			&i.Trigger,
			&i.Triggerdata,
			&i.Updated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT tasks.created, tasks.id, tasks.name, tasks.open, tasks.owner, tasks.ticket, tasks.updated,
       users.name       as owner_name,
       tickets.name     as ticket_name,
       tickets.type     as ticket_type,
       COUNT(*) OVER () as total_count
FROM tasks
         LEFT JOIN users ON users.id = tasks.owner
         LEFT JOIN tickets ON tickets.id = tasks.ticket
WHERE ticket = ?1
   OR ?1 = ''
ORDER BY tasks.created DESC
LIMIT ?3 OFFSET ?2
`

type ListTasksParams struct {
	Ticket string `json:"ticket"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type ListTasksRow struct {
	Created    string         `json:"created"`
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Open       bool           `json:"open"`
	Owner      string         `json:"owner"`
	Ticket     string         `json:"ticket"`
	Updated    string         `json:"updated"`
	OwnerName  sql.NullString `json:"owner_name"`
	TicketName sql.NullString `json:"ticket_name"`
	TicketType sql.NullString `json:"ticket_type"`
	TotalCount int64          `json:"total_count"`
}

func (q *ReadQueries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, arg.Ticket, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.Created,
			&i.ID,
			&i.Name,
			&i.Open,
			&i.Owner,
			&i.Ticket,
			&i.Updated,
			&i.OwnerName,
			&i.TicketName,
			&i.TicketType,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT tickets.created, tickets.description, tickets.id, tickets.name, tickets.open, tickets.owner, tickets.resolution, tickets.schema, tickets.state, tickets.type, tickets.updated,
       users.name       as owner_name,
       types.singular   as type_singular,
       types.plural     as type_plural,
       COUNT(*) OVER () as total_count
FROM tickets
         LEFT JOIN users ON users.id = tickets.owner
         LEFT JOIN types ON types.id = tickets.type
ORDER BY tickets.created DESC
LIMIT ?2 OFFSET ?1
`

type ListTicketsParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListTicketsRow struct {
	Created      string         `json:"created"`
	Description  string         `json:"description"`
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Open         bool           `json:"open"`
	Owner        string         `json:"owner"`
	Resolution   string         `json:"resolution"`
	Schema       string         `json:"schema"`
	State        string         `json:"state"`
	Type         string         `json:"type"`
	Updated      string         `json:"updated"`
	OwnerName    sql.NullString `json:"owner_name"`
	TypeSingular sql.NullString `json:"type_singular"`
	TypePlural   sql.NullString `json:"type_plural"`
	TotalCount   int64          `json:"total_count"`
}

func (q *ReadQueries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]ListTicketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTickets, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsRow
	for rows.Next() {
		var i ListTicketsRow
		if err := rows.Scan(
			&i.Created,
			&i.Description,
			&i.ID,
			&i.Name,
			&i.Open,
			&i.Owner,
			&i.Resolution,
			&i.Schema,
			&i.State,
			&i.Type,
			&i.Updated,
			&i.OwnerName,
			&i.TypeSingular,
			&i.TypePlural,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeline = `-- name: ListTimeline :many
SELECT timeline.created, timeline.id, timeline.message, timeline.ticket, timeline.time, timeline.updated, COUNT(*) OVER () as total_count
FROM timeline
WHERE ticket = ?1
   OR ?1 = ''
ORDER BY timeline.created DESC
LIMIT ?3 OFFSET ?2
`

type ListTimelineParams struct {
	Ticket string `json:"ticket"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type ListTimelineRow struct {
	Created    string `json:"created"`
	ID         string `json:"id"`
	Message    string `json:"message"`
	Ticket     string `json:"ticket"`
	Time       string `json:"time"`
	Updated    string `json:"updated"`
	TotalCount int64  `json:"total_count"`
}

func (q *ReadQueries) ListTimeline(ctx context.Context, arg ListTimelineParams) ([]ListTimelineRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimeline, arg.Ticket, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineRow
	for rows.Next() {
		var i ListTimelineRow
		if err := rows.Scan(
			&i.Created,
			&i.ID,
			&i.Message,
			&i.Ticket,
			&i.Time,
			&i.Updated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypes = `-- name: ListTypes :many
SELECT types.created, types.icon, types.id, types.plural, types.schema, types.singular, types.updated, COUNT(*) OVER () as total_count
FROM types
ORDER BY created DESC
LIMIT ?2 OFFSET ?1
`

type ListTypesParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListTypesRow struct {
	Created    string `json:"created"`
	Icon       string `json:"icon"`
	ID         string `json:"id"`
	Plural     string `json:"plural"`
	Schema     string `json:"schema"`
	Singular   string `json:"singular"`
	Updated    string `json:"updated"`
	TotalCount int64  `json:"total_count"`
}

func (q *ReadQueries) ListTypes(ctx context.Context, arg ListTypesParams) ([]ListTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTypes, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTypesRow
	for rows.Next() {
		var i ListTypesRow
		if err := rows.Scan(
			&i.Created,
			&i.Icon,
			&i.ID,
			&i.Plural,
			&i.Schema,
			&i.Singular,
			&i.Updated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.permissions, g.created, g.updated, uer.group_type, COUNT(*) OVER () as total_count
FROM user_effective_groups uer
         JOIN groups AS g ON g.id = uer.group_id
WHERE uer.user_id = ?1
ORDER BY g.name DESC
`

type ListUserGroupsRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Permissions string `json:"permissions"`
	Created     string `json:"created"`
	Updated     string `json:"updated"`
	GroupType   string `json:"group_type"`
	TotalCount  int64  `json:"total_count"`
}

func (q *ReadQueries) ListUserGroups(ctx context.Context, userID string) ([]ListUserGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsRow
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Permissions,
			&i.Created,
			&i.Updated,
			&i.GroupType,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissions = `-- name: ListUserPermissions :many
SELECT user_effective_permissions.permission
FROM user_effective_permissions
WHERE user_id = ?1
ORDER BY permission
`

func (q *ReadQueries) ListUserPermissions(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT users.avatar, users.created, users.email, users.id, users.lastresetsentat, users.lastverificationsentat, users.name, users.passwordhash, users.tokenkey, users.updated, users.username, users.verified, COUNT(*) OVER () as total_count
FROM users
WHERE id != 'system'
ORDER BY users.created DESC
LIMIT ?2 OFFSET ?1
`

type ListUsersParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListUsersRow struct {
	Avatar                 string `json:"avatar"`
	Created                string `json:"created"`
	Email                  string `json:"email"`
	ID                     string `json:"id"`
	Lastresetsentat        string `json:"lastresetsentat"`
	Lastverificationsentat string `json:"lastverificationsentat"`
	Name                   string `json:"name"`
	Passwordhash           string `json:"passwordhash"`
	Tokenkey               string `json:"tokenkey"`
	Updated                string `json:"updated"`
	Username               string `json:"username"`
	Verified               bool   `json:"verified"`
	TotalCount             int64  `json:"total_count"`
}

func (q *ReadQueries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.Avatar,
			&i.Created,
			&i.Email,
			&i.ID,
			&i.Lastresetsentat,
			&i.Lastverificationsentat,
			&i.Name,
			&i.Passwordhash,
			&i.Tokenkey,
			&i.Updated,
			&i.Username,
			&i.Verified,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT webhooks.collection, webhooks.created, webhooks.destination, webhooks.id, webhooks.name, webhooks.updated, COUNT(*) OVER () as total_count
FROM webhooks
ORDER BY created DESC
LIMIT ?2 OFFSET ?1
`

type ListWebhooksParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListWebhooksRow struct {
	Collection  string `json:"collection"`
	Created     string `json:"created"`
	Destination string `json:"destination"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	Updated     string `json:"updated"`
	TotalCount  int64  `json:"total_count"`
}

func (q *ReadQueries) ListWebhooks(ctx context.Context, arg ListWebhooksParams) ([]ListWebhooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooks, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhooksRow
	for rows.Next() {
		var i ListWebhooksRow
		if err := rows.Scan(
			&i.Collection,
			&i.Created,
			&i.Destination,
			&i.ID,
			&i.Name,
			&i.Updated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const param = `-- name: Param :one
SELECT id, "key", value, created, updated
FROM _params
WHERE _params.key = ?1
`

func (q *ReadQueries) Param(ctx context.Context, key string) (Param, error) {
	row := q.db.QueryRowContext(ctx, param, key)
	var i Param
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const searchTickets = `-- name: SearchTickets :many
SELECT id,
       name,
       created,
       description,
       open,
       type,
       state,
       owner_name,
       COUNT(*) OVER () as total_count
FROM ticket_search
WHERE (?1 = '' OR (name LIKE '%' || ?1 || '%'
    OR description LIKE '%' || ?1 || '%'
    OR comment_messages LIKE '%' || ?1 || '%'
    OR file_names LIKE '%' || ?1 || '%'
    OR link_names LIKE '%' || ?1 || '%'
    OR link_urls LIKE '%' || ?1 || '%'
    OR task_names LIKE '%' || ?1 || '%'
    OR timeline_messages LIKE '%' || ?1 || '%'))
  AND (?2 IS NULL OR type = ?2)
  AND (?3 IS NULL OR open = ?3)
LIMIT ?5 OFFSET ?4
`

type SearchTicketsParams struct {
	Query  interface{} `json:"query"`
	Type   interface{} `json:"type"`
	Open   interface{} `json:"open"`
	Offset int64       `json:"offset"`
	Limit  int64       `json:"limit"`
}

type SearchTicketsRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Created     string         `json:"created"`
	Description string         `json:"description"`
	Open        bool           `json:"open"`
	Type        string         `json:"type"`
	State       string         `json:"state"`
	OwnerName   sql.NullString `json:"owner_name"`
	TotalCount  int64          `json:"total_count"`
}

func (q *ReadQueries) SearchTickets(ctx context.Context, arg SearchTicketsParams) ([]SearchTicketsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTickets,
		arg.Query,
		arg.Type,
		arg.Open,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTicketsRow
	for rows.Next() {
		var i SearchTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Created,
			&i.Description,
			&i.Open,
			&i.Type,
			&i.State,
			&i.OwnerName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const systemUser = `-- name: SystemUser :one
SELECT avatar, created, email, id, lastresetsentat, lastverificationsentat, name, passwordhash, tokenkey, updated, username, verified
FROM users
WHERE id = 'system'
`

func (q *ReadQueries) SystemUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, systemUser)
	var i User
	err := row.Scan(
		&i.Avatar,
		&i.Created,
		&i.Email,
		&i.ID,
		&i.Lastresetsentat,
		&i.Lastverificationsentat,
		&i.Name,
		&i.Passwordhash,
		&i.Tokenkey,
		&i.Updated,
		&i.Username,
		&i.Verified,
	)
	return i, err
}

const ticket = `-- name: Ticket :one

SELECT tickets.created, tickets.description, tickets.id, tickets.name, tickets.open, tickets.owner, tickets.resolution, tickets.schema, tickets.state, tickets.type, tickets.updated, users.name as owner_name, types.singular as type_singular, types.plural as type_plural
FROM tickets
         LEFT JOIN users ON users.id = tickets.owner
         LEFT JOIN types ON types.id = tickets.type
WHERE tickets.id = ?1
`

type TicketRow struct {
	Created      string         `json:"created"`
	Description  string         `json:"description"`
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Open         bool           `json:"open"`
	Owner        string         `json:"owner"`
	Resolution   string         `json:"resolution"`
	Schema       string         `json:"schema"`
	State        string         `json:"state"`
	Type         string         `json:"type"`
	Updated      string         `json:"updated"`
	OwnerName    sql.NullString `json:"owner_name"`
	TypeSingular sql.NullString `json:"type_singular"`
	TypePlural   sql.NullString `json:"type_plural"`
}

// -----------------------------------------------------------------
func (q *ReadQueries) Ticket(ctx context.Context, id string) (TicketRow, error) {
	row := q.db.QueryRowContext(ctx, ticket, id)
	var i TicketRow
	err := row.Scan(
		&i.Created,
		&i.Description,
		&i.ID,
		&i.Name,
		&i.Open,
		&i.Owner,
		&i.Resolution,
		&i.Schema,
		&i.State,
		&i.Type,
		&i.Updated,
		&i.OwnerName,
		&i.TypeSingular,
		&i.TypePlural,
	)
	return i, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT avatar, created, email, id, lastresetsentat, lastverificationsentat, name, passwordhash, tokenkey, updated, username, verified
FROM users
WHERE email = ?1
  AND id != 'system'
`

func (q *ReadQueries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.Avatar,
		&i.Created,
		&i.Email,
		&i.ID,
		&i.Lastresetsentat,
		&i.Lastverificationsentat,
		&i.Name,
		&i.Passwordhash,
		&i.Tokenkey,
		&i.Updated,
		&i.Username,
		&i.Verified,
	)
	return i, err
}

const userByUserName = `-- name: UserByUserName :one
SELECT avatar, created, email, id, lastresetsentat, lastverificationsentat, name, passwordhash, tokenkey, updated, username, verified
FROM users
WHERE username = ?1
  AND id != 'system'
`

func (q *ReadQueries) UserByUserName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByUserName, username)
	var i User
	err := row.Scan(
		&i.Avatar,
		&i.Created,
		&i.Email,
		&i.ID,
		&i.Lastresetsentat,
		&i.Lastverificationsentat,
		&i.Name,
		&i.Passwordhash,
		&i.Tokenkey,
		&i.Updated,
		&i.Username,
		&i.Verified,
	)
	return i, err
}
