run:
  go: "1.19"
  timeout: 5m
  skip-dirs:
    - generated
    - testserver
linters:
  enable:
    - asciicheck
    - containedctx
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - ireturn
    - misspell
    - nakedret
    - nilnil
    - nlreturn
    - nolintlint
    - paralleltest
    - predeclared
    - promlinter
    - revive
    - tenv
    - thelper
    - unconvert
    - whitespace

    - bodyclose
    - gosimple
    - nilerr

    - staticcheck
    - stylecheck
    - tparallel
    - unparam
    - unused

  disable:
    # go 1.18
    #- bodyclose
    #- contextcheck
    #- gosimple
    #- nilerr
    #- noctx
    #- rowserrcheck
    #- sqlclosecheck
    #- staticcheck
    #- stylecheck
    #- tparallel
    #- unparam
    #- unused
    #- wastedassign
    - sqlclosecheck
    - rowserrcheck
    - wastedassign

    # complexity
    - cyclop
    - gocognit
    - gocyclo
    - maintidx
    - nestif

    # disable
    - contextcheck
    - dupl
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - godox
    - goerr113
    - gomnd
    - gomoddirectives
    - lll
    - makezero
    - noctx
    - prealloc
    - structcheck
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cugu/maut)
  ireturn:
    allow:
      - error
      - context.Context
      - go-driver.Cursor
      - go-driver.Collection
      - go-driver.Database
      - go-driver.Client
      - chi.Router
issues:
  exclude-rules:
    - linters:
        - errchkjson
      text: "encoding/json.Marshal"
    - linters: [ containedctx ]
      path: context_test.go
    - linters: [ govet ]
      path: _test.go
    - linters: [ ireturn ]
      path: example