---
server:
  host: 0.0.0.0
  port: 8082
default_redirection_url: "http://localhost:8080/auth/callback"

log:
  format: text

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor

session:
  domain: localhost

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

identity_providers:
  oidc:
    cors:
      # allowed_origins_from_client_redirect_uris: true
      allowed_origins: [ "*" ]
    clients:
      - id: "catalyst"
        description: API
        secret: "secret"
        public: false
        authorization_policy: one_factor
        scopes: [ openid, email, profile ]
        redirect_uris:
          - "http://localhost:8080/auth/callback"
        userinfo_signing_algorithm: none
